apiVersion: v1
description: pgAdmin4 is a web based administration tool for PostgreSQL database
name: pgadmin4
version: 1.2.5
appVersion: 4.19.0
home: https://www.pgadmin.org/
source: https://github.com/rowanruseler/helm-charts
maintainers:
  - name: rowanruseler
    email: rowanruseler@gmail.com
