apiVersion: v2
description: pgAdmin4 is a web based administration tool for PostgreSQL database
name: pgadmin4
version: 1.42.0
appVersion: 9.2
keywords:
  - pgadmin
  - postgres
  - database
  - sql
home: https://www.pgadmin.org/
icon: https://wiki.postgresql.org/images/3/30/PostgreSQL_logo.3colors.120x120.png
sources:
  - https://github.com/rowanruseler/helm-charts
license: Apache-2.0
maintainers:
  - name: rowanruseler
    email: rowanruseler@gmail.com
