apiVersion: v1
description: pgAdmin4 is a web based administration tool for PostgreSQL database
name: pgadmin4
version: 1.19.0
appVersion: "7.8"
keywords:
  - pgadmin
  - postgres
  - database
  - sql
home: https://www.pgadmin.org/
icon: https://wiki.postgresql.org/images/3/30/PostgreSQL_logo.3colors.120x120.png
sources:
  - https://github.com/rowanruseler/helm-charts
maintainers:
  - name: rowanruseler
    email: rowanruseler@gmail.com
