{{- if .Values.httpRoute.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "pgadmin.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pgadmin.labels" . | nindent 4 }}
  {{- with .Values.httpRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    {{- toYaml .Values.httpRoute.parentRefs | nindent 4 }}
  hostnames:
    {{- toYaml .Values.httpRoute.hostnames | nindent 4 }}
  rules:
    - matches:
      {{- if .Values.httpRoute.matches }}
        {{- toYaml .Values.httpRoute.matches | nindent 8 }}
      {{- else }}
        - path:
            type: PathPrefix
            value: /
      {{- end }}
      backendRefs:
        - name: {{ include "pgadmin.fullname" . }}
          port: {{ .Values.service.port }}
{{- end }}
