{{- if and .Values.serverDefinitions.enabled (eq .Values.serverDefinitions.resourceType "Secret") .Values.serverDefinitions.servers (not .Values.serverDefinitions.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pgadmin.fullname" . }}-server-definitions
  namespace: {{ include "pgadmin.namespaceName" . }}
  labels:
    {{- include "pgadmin.labels" . | nindent 4 }}
  {{- if .Values.serverDefinitions.annotations }}
  annotations:
    {{- .Values.serverDefinitions.annotations | toYaml | nindent 4 }}
  {{- end }}
type: Opaque
{{- if .Values.serverDefinitions.useStringData }}
stringData:
  servers.json: |-
    {{- include "pgadmin.serverDefinitions" . | trim | nindent 4 }}
{{- else }}
data:
  servers.json: {{ include "pgadmin.serverDefinitions" . | trim | b64enc | quote }}
{{- end }}
{{- end }}
