{{- if and .Values.serverDefinitions.enabled (eq .Values.serverDefinitions.resourceType "ConfigMap") .Values.serverDefinitions.servers (not .Values.serverDefinitions.existingConfigmap) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pgadmin.fullname" . }}-server-definitions
  namespace: {{ include "pgadmin.namespaceName" . }}
  labels:
    {{- include "pgadmin.labels" . | nindent 4 }}
  {{- if .Values.serverDefinitions.annotations }}
  annotations:
    {{- .Values.serverDefinitions.annotations | toYaml | nindent 4 }}
  {{- end }}
data:
  servers.json: |-
    {{ include "pgadmin.serverDefinitions" . | nindent 4 | trim }}
{{- end }}
