{{/*
DEPRECATED

This template used to render the pgAdmin server definitions ConfigMap.
If you want `servers.json` via ConfigMap, create it using `configMaps` and mount it via `extraVolumes` + `extraVolumeMounts`.
*/}}
